/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegopong;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.Timer;

public class Frmpong extends javax.swing.JFrame implements KeyListener
{

    int pelotax = 385;
    int pelotay = 300;
    int direccionx = 1;
    int direcciony = 1;  
    int paleta1 = 225;
    int paleta2 = 225;
   
    
    public void keyTyped(KeyEvent e) {}
    public void keyReleased(KeyEvent e) {}
    public void keyPressed(KeyEvent e)
    {
       int paleta = e.getKeyCode();
       System.out.println(paleta);
       
       if (paleta == 38)
       {
           if (paleta1 > 40)
           {             
                paleta1 -= 10;
           }       
       }
       
        if (paleta == 40)
       {
           if (paleta1 < 440)
           {     
                paleta1 += 10;
           }       
       }
        if (paleta == 87)
       {
           if (paleta2 > 40)
           {    
                paleta2 -= 10;
           }       
       }
        if (paleta == 83)
       {
           if (paleta2 < 440)
           {        
                paleta2 += 10;
           }       
       }
    }   
    
    public void paint (Graphics g)
    {
        super.paint (g);
 
        g.setColor(Color.red);
        g.fillRect(20 , paleta1 , 50 , 200);
        g.fillRect(750 , paleta2 , 50 , 200);
        g.setColor(Color.black);
        g.fillOval(pelotax , pelotay , 50 , 50);
        g.setFont(new Font ("Arial" , Font.BOLD , 20));
        g.drawString("0" , 250 , 75);
        g.drawString("0" , 550 , 75);
        
        
    }
    Timer temporizador = new Timer(10, new ActionListener()
    {
        public void actionPerformed (ActionEvent e)
        {
            if (pelotax >= 750)
            {
                if (pelotay + 25 > paleta1 && pelotay + 25 < paleta1 + 200)
                {
                    direccionx *= -1;
                }
                else
                {
                    pelotax = 275;
                    pelotay = 385;
                    direccionx = 1;
                }
            }
               
            if (pelotax <= 100)
            {
                if (pelotay + 25 > paleta2 && pelotay + 25 < paleta2 + 200)
                {
                    direccionx *= 1;
                }
                else
                {
                    pelotax = 275;
                    pelotay = 385;
                    direccionx = 1;
                }
            }    
                
            if(pelotay >= 550 || pelotay <= 40)
            {
                direcciony *=-1;
            }
            pelotay += 5 * direcciony;
            repaint ();
            
            if(pelotay >= 750 || pelotay < 100 )
            {
                direcciony *=-1;
            }
            pelotax += 5 * direccionx;
            repaint();
        }
    });
    public Frmpong() 
    
    {
        
        initComponents();
        temporizador.start();
        addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmpong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmpong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmpong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmpong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmpong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
