/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neptuno;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EQÚIPO
 */
public class FrmCompañíadeEnviós extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCompañíadeEnviós
     */
    public FrmCompañíadeEnviós() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnnuevo = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttelf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtbusquedaid = new javax.swing.JTextField();
        txtbusquedacompañía = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCompañías = new javax.swing.JTable();
        txtidcompañía = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        btneliminar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/nuevo.png"))); // NOI18N
        btnnuevo.setPreferredSize(new java.awt.Dimension(16, 16));
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/imprimir.jpg"))); // NOI18N
        btnimprimir.setPreferredSize(new java.awt.Dimension(16, 16));
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/save.png"))); // NOI18N
        btnguardar.setEnabled(false);
        btnguardar.setPreferredSize(new java.awt.Dimension(16, 16));
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Mantenimiento");

        jLabel2.setText("idCompañíadeenviós");

        txttelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelfActionPerformed(evt);
            }
        });

        jLabel3.setText("NombreCompañía");

        jLabel13.setText("Busqueda");

        jLabel15.setText("NombreCompañía");

        txtbusquedaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusquedaidKeyReleased(evt);
            }
        });

        txtbusquedacompañía.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusquedacompañíaKeyReleased(evt);
            }
        });

        jLabel11.setText("Teléfono");

        tblCompañías.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCompañías.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCompañíasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCompañías);

        txtidcompañía.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidcompañíaActionPerformed(evt);
            }
        });
        txtidcompañía.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidcompañíaKeyReleased(evt);
            }
        });

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/delete.png"))); // NOI18N
        btneliminar.setEnabled(false);
        btneliminar.setPreferredSize(new java.awt.Dimension(16, 16));
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/editar.png"))); // NOI18N
        btneditar.setEnabled(false);
        btneditar.setPreferredSize(new java.awt.Dimension(16, 16));
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        jLabel4.setText("idCompañíadeenviós");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtidcompañía, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txttelf, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtbusquedaid, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(11, 11, 11)
                        .addComponent(txtbusquedacompañía, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtidcompañía, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addComponent(txttelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtbusquedaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbusquedacompañía, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void txttelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelfActionPerformed

    private void txtidcompañíaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidcompañíaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidcompañíaActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        txtidcompañía.setText("");
        txtnombre.setText("");
        txttelf.setText("");
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        CompañíaEnvios envios = new CompañíaEnvios("root" , "eran" , "neptuno2017_3" , "localhost");
        envios.conectarCompañíaEnvios();
        JOptionPane.showMessageDialog(null , envios.guardarCompañíaEnvios(txtidcompañía.getText() , txtnombre.getText() , txttelf.getText() ));
        envios.cerrarCompañíaEnvios();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        CompañíaEnvios envios = new CompañíaEnvios("root" , "eran" , "neptuno2017_3" , "localhost");
        envios.conectarCompañíaEnvios();
        JOptionPane.showMessageDialog(null , envios.eliminarCompañíaEnvios(txtidcompañía.getText()));
        envios.cerrarCompañíaEnvios();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        CompañíaEnvios envios = new CompañíaEnvios("root" , "eran" , "neptuno2017_3" , "localhost");
        envios.conectarCompañíaEnvios();
        JOptionPane.showMessageDialog(null , envios.actualizarCompañíaEnvios(txtidcompañía.getText() , txtnombre.getText() , txttelf.getText() ));
        envios.cerrarCompañíaEnvios();
    }//GEN-LAST:event_btneditarActionPerformed

    private void txtbusquedaidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaidKeyReleased
        try 
        {
            CompañíaEnvios envios = new CompañíaEnvios("root" , "eran" , "neptuno2017_3" , "localhost");
            envios.conectarCompañíaEnvios();
            ResultSet rsEnvios = envios.buscarPorId(txtbusquedaid.getText());
            //Para establecer el modelo al JTable
            
            DefaultTableModel modelo = new DefaultTableModel();
            tblCompañías.setModel(modelo);
            
            //Para conectarnos a nuestra base de datos
            
            ResultSetMetaData rsMd = rsEnvios.getMetaData();
            
            //La cantidad de columnas que tiene la consulta
            
            int cantidadColumnas = rsMd.getColumnCount();
            
            //Establecer como cabezeras el nombre de las colimnas
            
            for (int posicion = 1 ; posicion <= cantidadColumnas ; posicion ++)
            {
                modelo.addColumn(rsMd.getColumnLabel(posicion));
            }
            //Creando las filas para el JTable
            
            while (rsEnvios.next())
            {
                Object[] fila = new Object[cantidadColumnas];
                for (int posicion = 0; posicion < cantidadColumnas; posicion ++)
                {
                    fila[posicion] = rsEnvios.getObject(posicion + 1);
                }
                modelo.addRow(fila);
                
            }  
            envios.cerrarCompañíaEnvios();
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(FrmCompañíadeEnviós.class.getName()).log(Level.SEVERE , null , ex);
        }
    }//GEN-LAST:event_txtbusquedaidKeyReleased

    private void txtbusquedacompañíaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedacompañíaKeyReleased
        try 
        {
            CompañíaEnvios envios = new CompañíaEnvios("root" , "eran" , "neptuno2017_3" , "localhost");
            envios.conectarCompañíaEnvios();
            ResultSet rsCompañía = envios.buscarPorNombreCompañía(txtbusquedacompañía.getText());
            //Para establecer el modelo al JTable
            
            DefaultTableModel modelo = new DefaultTableModel();
            tblCompañías.setModel(modelo);
            
            //Para conectarnos a nuestra base de datos
            
            ResultSetMetaData rsMd = rsCompañía.getMetaData();
            
            //La cantidad de columnas que tiene la consulta
            
            int cantidadColumnas = rsMd.getColumnCount();
            
            //Establecer como cabezeras el nombre de las colimnas
            
            for (int posicion = 1 ; posicion <= cantidadColumnas ; posicion ++)
            {
                modelo.addColumn(rsMd.getColumnLabel(posicion));
            }
            //Creando las filas para el JTable
            
            while (rsCompañía.next())
            {
                Object[] fila = new Object[cantidadColumnas];
                for (int posicion = 0; posicion < cantidadColumnas; posicion ++)
                {
                    fila[posicion] = rsCompañía.getObject(posicion + 1);
                }
                modelo.addRow(fila);
                
            }  
            envios.cerrarCompañíaEnvios();
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(FrmCompañíadeEnviós.class.getName()).log(Level.SEVERE , null , ex);
        }
    }//GEN-LAST:event_txtbusquedacompañíaKeyReleased

    private void tblCompañíasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCompañíasMouseClicked
        txtidcompañía.setText(String.valueOf(tblCompañías.getValueAt(tblCompañías.getSelectedRow() , 0)));
        txtnombre.setText(String.valueOf(tblCompañías.getValueAt(tblCompañías.getSelectedRow() , 1)));
        txttelf.setText(String.valueOf(tblCompañías.getValueAt(tblCompañías.getSelectedRow() , 2)));
        
        if (!txtidcompañía.getText().equals("") && !txtnombre.getText().equals(""))
        {
            btneliminar.setEnabled(true);
            btnguardar.setEnabled(true);
            btneditar.setEnabled(true);
            
        }
        else
        {
            btneliminar.setEnabled(false);
            
        }
    }//GEN-LAST:event_tblCompañíasMouseClicked

    private void txtidcompañíaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidcompañíaKeyReleased
        if (!txtidcompañía.getText().equals("") && !txtnombre.getText().equals(""))
        {
            
            btnguardar.setEnabled(true);
            btneditar.setEnabled(true);
        }
        else
        {
            
            btnguardar.setEnabled(false);
            btneditar.setEnabled(false);
            btneliminar.setEnabled(false);
        }
    }//GEN-LAST:event_txtidcompañíaKeyReleased

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased
       if (!txtidcompañía.getText().equals("") && !txtnombre.getText().equals(""))
        {
            
            btnguardar.setEnabled(true);
            btneditar.setEnabled(true);
        }
        else
        {
            
            btnguardar.setEnabled(false);
            btneditar.setEnabled(false);
            btneliminar.setEnabled(false);
        }
    }//GEN-LAST:event_txtnombreKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCompañías;
    private javax.swing.JTextField txtbusquedacompañía;
    private javax.swing.JTextField txtbusquedaid;
    private javax.swing.JTextField txtidcompañía;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelf;
    // End of variables declaration//GEN-END:variables
}
