/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neptuno;

import java.io.File;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EQÚIPO
 */
public class FrmEmpleados extends javax.swing.JInternalFrame 
{

    /**
     * Creates new form FrmEmpleados
     */
    public FrmEmpleados() 
    {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnnuevo = new javax.swing.JButton();
        txtfechanac = new javax.swing.JTextField();
        btnimprimir = new javax.swing.JButton();
        txtfechacont = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        txtdireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtciudad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtregion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtbusquedacliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtbusquedafecha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        txtidempleado = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtcargo = new javax.swing.JTextField();
        btneliminar = new javax.swing.JButton();
        txtdtratamiento = new javax.swing.JTextField();
        btneditar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtpais = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        txtfoto = new javax.swing.JTextField();
        txtnotas = new javax.swing.JTextField();
        txtjefe = new javax.swing.JTextField();
        txtext = new javax.swing.JTextField();
        btnfoto = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();

        setClosable(true);

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/nuevo.png"))); // NOI18N
        btnnuevo.setPreferredSize(new java.awt.Dimension(16, 16));
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        txtfechanac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechanacActionPerformed(evt);
            }
        });
        txtfechanac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfechanacKeyReleased(evt);
            }
        });

        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/imprimir.jpg"))); // NOI18N
        btnimprimir.setPreferredSize(new java.awt.Dimension(16, 16));
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        txtfechacont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfechacontKeyReleased(evt);
            }
        });

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/save.png"))); // NOI18N
        btnguardar.setEnabled(false);
        btnguardar.setPreferredSize(new java.awt.Dimension(16, 16));
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Mantenimiento");

        txtciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtciudadActionPerformed(evt);
            }
        });

        jLabel2.setText("idEmpleado");

        txtregion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregionActionPerformed(evt);
            }
        });

        jLabel3.setText("FechaNacimiento");

        jLabel4.setText("Nombre");

        jLabel5.setText("Cargo");

        txtcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodActionPerformed(evt);
            }
        });

        jLabel13.setText("Busqueda");

        jLabel6.setText("Tratamiento");

        jLabel14.setText("idEmpleado");

        jLabel7.setText("FechaNacimiento");

        jLabel15.setText("Apellidos");

        txtbusquedacliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusquedaclienteKeyReleased(evt);
            }
        });

        jLabel8.setText("FechaContratación");

        txtbusquedafecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusquedafechaKeyReleased(evt);
            }
        });

        jLabel9.setText("Dirección");

        jLabel10.setText("Ciudad");

        jLabel11.setText("Región");

        jLabel12.setText("CodPostal");

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEmpleados);

        txtidempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidempleadoActionPerformed(evt);
            }
        });
        txtidempleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidempleadoKeyReleased(evt);
            }
        });

        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtapellidoKeyReleased(evt);
            }
        });

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
        });

        txtcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcargoActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/delete.png"))); // NOI18N
        btneliminar.setEnabled(false);
        btneliminar.setPreferredSize(new java.awt.Dimension(16, 16));
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        txtdtratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdtratamientoActionPerformed(evt);
            }
        });

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/editar.png"))); // NOI18N
        btneditar.setEnabled(false);
        btneditar.setPreferredSize(new java.awt.Dimension(16, 16));
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        jLabel16.setText("País");

        txtpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaisActionPerformed(evt);
            }
        });

        jLabel17.setText("TelDomicilio");

        jLabel18.setText("Extensión");

        jLabel19.setText("Foto");

        jLabel20.setText("Notas");

        jLabel21.setText("Jefe");

        txttel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelActionPerformed(evt);
            }
        });

        txtfoto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfotoKeyReleased(evt);
            }
        });

        txtjefe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjefeKeyReleased(evt);
            }
        });

        btnfoto.setText("...");
        btnfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtfechanac, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfechacont, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtciudad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtregion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txtidempleado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtapellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcargo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdtratamiento, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcod, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtfoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(txtnotas, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtjefe))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtext, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(txttel)
                                    .addComponent(txtpais))))
                        .addGap(43, 43, 43)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(27, 27, 27)
                        .addComponent(txtbusquedacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtbusquedafecha, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(txtidempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel2)
                                                                .addComponent(jLabel16))
                                                            .addComponent(txtpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel15)
                                                                .addComponent(jLabel17))
                                                            .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel18)
                                                        .addComponent(txtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel19)
                                                .addComponent(txtfoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnfoto))))
                                    .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(txtnotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtdtratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addComponent(jLabel21)
                            .addComponent(txtjefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtfechanac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23))
                                            .addComponent(txtfechacont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(23, 23, 23))
                                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
                            .addComponent(txtciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addComponent(txtregion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel3)
                    .addComponent(txtbusquedacliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbusquedafecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfechanacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechanacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechanacActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void txtciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtciudadActionPerformed

    private void txtregionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregionActionPerformed

    private void txtcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodActionPerformed

    private void txtidempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidempleadoActionPerformed

    private void txtcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcargoActionPerformed

    private void txtdtratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdtratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdtratamientoActionPerformed

    private void txtpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaisActionPerformed

    private void txttelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        txtidempleado.setText("");
        txtapellido.setText("");
        txtnombre.setText("");
        txtcargo.setText("");
        txtdtratamiento.setText("");
        txtfechanac.setText("");
        txtfechacont.setText("");
        txtdireccion.setText("");
        txtciudad.setText("");
        txtregion.setText("");
        txtcod.setText("");
        txtpais.setText("");
        txttel.setText("");
        txtext.setText("");
        txtfoto.setText("");
        txtnotas.setText("");
        txtjefe.setText("");
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        Empleados empleado = new Empleados("root" , "eran" , "neptuno2017_3" , "localhost");
        empleado.conectarEmpleados();
        JOptionPane.showMessageDialog(null , empleado.guardarEmpleados(txtidempleado.getText() , txtapellido.getText() , txtnombre.getText() , txtcargo.getText() , txtdtratamiento.getText() , txtfechanac.getText() , txtfechacont.getText() , txtdireccion.getText() , txtciudad.getText() , txtregion.getText() , txtcod.getText() , txtpais.getText() , txttel.getText() , txtext.getText() , txtfoto.getText() , txtnotas.getText() , txtjefe.getText()));
        empleado.cerrarEmpleados();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        Empleados empleado = new Empleados("root" , "eran" , "neptuno2017_3" , "localhost");
        empleado.conectarEmpleados();
        JOptionPane.showMessageDialog(null , empleado.eliminarEmpleados(txtidempleado.getText()));
        empleado.cerrarEmpleados();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        Empleados empleado = new Empleados("root" , "eran" , "neptuno2017_3" , "localhost");
        empleado.conectarEmpleados();
        JOptionPane.showMessageDialog(null , empleado.actualizarEmpleados(txtidempleado.getText() , txtapellido.getText() , txtnombre.getText() , txtcargo.getText() , txtdtratamiento.getText() , txtfechanac.getText() , txtfechacont.getText() , txtdireccion.getText() , txtciudad.getText() , txtregion.getText() , txtcod.getText() , txtpais.getText() , txttel.getText() , txtext.getText() , txtfoto.getText() , txtnotas.getText() , txtjefe.getText()));
        empleado.cerrarEmpleados();
    }//GEN-LAST:event_btneditarActionPerformed

    private void txtbusquedaclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaclienteKeyReleased
    try 
        {
            Empleados empleado = new Empleados("root" , "eran" , "neptuno2017_3" , "localhost");
            empleado.conectarEmpleados();
            ResultSet rsEmpleados = empleado.buscarPorId(txtbusquedacliente.getText());
            //Para establecer el modelo al JTable
            
            DefaultTableModel modelo = new DefaultTableModel();
            tblEmpleados.setModel(modelo);
            
            //Para conectarnos a nuestra base de datos
            
            ResultSetMetaData rsMd = rsEmpleados.getMetaData();
            
            //La cantidad de columnas que tiene la consulta
            
            int cantidadColumnas = rsMd.getColumnCount();
            
            //Establecer como cabezeras el nombre de las colimnas
            
            for (int posicion = 1 ; posicion <= cantidadColumnas ; posicion ++)
            {
                modelo.addColumn(rsMd.getColumnLabel(posicion));
            }
            //Creando las filas para el JTable
            
            while (rsEmpleados.next())
            {
                Object[] fila = new Object[cantidadColumnas];
                for (int posicion = 0; posicion < cantidadColumnas; posicion ++)
                {
                    fila[posicion] = rsEmpleados.getObject(posicion + 1);
                }
                modelo.addRow(fila);
                
            }  
            empleado.cerrarEmpleados();
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(FrmEmpleados.class.getName()).log(Level.SEVERE , null , ex);
        }
    }//GEN-LAST:event_txtbusquedaclienteKeyReleased

    private void txtbusquedafechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedafechaKeyReleased
try 
        {
            Empleados empleado = new Empleados("root" , "eran" , "neptuno2017_3" , "localhost");
            empleado.conectarEmpleados();
            ResultSet rsFecha = empleado.buscarPorFechaNacimiento(txtbusquedafecha.getText());
            //Para establecer el modelo al JTable
            
            DefaultTableModel modelo = new DefaultTableModel();
            tblEmpleados.setModel(modelo);
            
            //Para conectarnos a nuestra base de datos
            
            ResultSetMetaData rsMd = rsFecha.getMetaData();
            
            //La cantidad de columnas que tiene la consulta
            
            int cantidadColumnas = rsMd.getColumnCount();
            
            //Establecer como cabezeras el nombre de las colimnas
            
            for (int posicion = 1 ; posicion <= cantidadColumnas ; posicion ++)
            {
                modelo.addColumn(rsMd.getColumnLabel(posicion));
            }
            //Creando las filas para el JTable
            
            while (rsFecha.next())
            {
                Object[] fila = new Object[cantidadColumnas];
                for (int posicion = 0; posicion < cantidadColumnas; posicion ++)
                {
                    fila[posicion] = rsFecha.getObject(posicion + 1);
                }
                modelo.addRow(fila);
                
            }  
            empleado.cerrarEmpleados();
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(FrmEmpleados.class.getName()).log(Level.SEVERE , null , ex);
        }
    }//GEN-LAST:event_txtbusquedafechaKeyReleased

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        txtidempleado.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 0)));
        txtapellido.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 1)));
        txtnombre.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 2)));
        txtcargo.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 3)));
        txtdtratamiento.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 4)));
        txtfechanac.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 5)));
        txtfechacont.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 6)));
        txtdireccion.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 7)));
        txtciudad.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 8)));
        txtregion.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 9)));
        txtcod.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 10)));
        txtpais.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 11)));
        txttel.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 12)));
        txtext.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 13)));
        txtfoto.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 14)));
        txtnotas.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 15)));
        txtjefe.setText(String.valueOf(tblEmpleados.getValueAt(tblEmpleados.getSelectedRow() , 16)));
        
        if (!txtidempleado.getText().equals("") && !txtapellido.getText().equals("") && !txtnombre.getText().equals("") && !txtfechanac.getText().equals("") && !txtfechacont.getText().equals("") && !txtjefe.getText().equals(""))
        {
            btneliminar.setEnabled(true);
            btnguardar.setEnabled(true);
            btneditar.setEnabled(true);
            
        }
        else
        {
            btneliminar.setEnabled(false);
            
        }
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void txtidempleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidempleadoKeyReleased
    if (!txtidempleado.getText().equals("") && !txtapellido.getText().equals("") && !txtnombre.getText().equals("") && !txtfechanac.getText().equals("") && !txtfechacont.getText().equals("") && !txtjefe.getText().equals(""))
        {
            
            btnguardar.setEnabled(true);
            btneditar.setEnabled(true);
        }
        else
        {
            
            btnguardar.setEnabled(false);
            btneditar.setEnabled(false);
            btneliminar.setEnabled(false);
        }
    }//GEN-LAST:event_txtidempleadoKeyReleased

    private void txtapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyReleased
        if (!txtidempleado.getText().equals("") && !txtapellido.getText().equals("") && !txtnombre.getText().equals("") && !txtfechanac.getText().equals("") && !txtfechacont.getText().equals("") && !txtjefe.getText().equals(""))
        {
            
            btnguardar.setEnabled(true);
            btneditar.setEnabled(true);
        }
        else
        {
            
            btnguardar.setEnabled(false);
            btneditar.setEnabled(false);
            btneliminar.setEnabled(false);
        }
    }//GEN-LAST:event_txtapellidoKeyReleased

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased
    if (!txtidempleado.getText().equals("") && !txtapellido.getText().equals("") && !txtnombre.getText().equals("") && !txtfechanac.getText().equals("") && !txtfechacont.getText().equals("") && !txtjefe.getText().equals(""))
        {
            
            btnguardar.setEnabled(true);
            btneditar.setEnabled(true);
        }
        else
        {
            
            btnguardar.setEnabled(false);
            btneditar.setEnabled(false);
            btneliminar.setEnabled(false);
        }
        
        while(!txtnombre.getText().matches("([a-z]|[A-Z]|\\s)+") && txtnombre.getText().length()>0)
        {
                txtnombre.setText(txtnombre.getText().substring(0 ,txtnombre.getText().length()-1));
                JOptionPane.showMessageDialog(null, "Carater no válido", "Validación", JOptionPane.PLAIN_MESSAGE);
                
        }    }//GEN-LAST:event_txtnombreKeyReleased

    private void btnfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfotoActionPerformed
        JFileChooser chooser = new JFileChooser();
        File file = chooser.getCurrentDirectory();
        chooser.setCurrentDirectory(file);
        if ((chooser.showOpenDialog(this.txtfoto))!=JFileChooser.APPROVE_OPTION) return;
        File file2 = chooser.getSelectedFile();
        this.txtfoto.setText(file2.getPath());
        lblFoto.setIcon ( new ImageIcon (txtfoto.getText()));
      
        
    }//GEN-LAST:event_btnfotoActionPerformed

    private void txtfechanacKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfechanacKeyReleased
    if (!txtidempleado.getText().equals("") && !txtapellido.getText().equals("") && !txtnombre.getText().equals("") && !txtfechanac.getText().equals("") && !txtfechacont.getText().equals("") && !txtjefe.getText().equals(""))
        {
            
            btnguardar.setEnabled(true);
            btneditar.setEnabled(true);
        }
        else
        {
            
            btnguardar.setEnabled(false);
            btneditar.setEnabled(false);
            btneliminar.setEnabled(false);
        }
    }//GEN-LAST:event_txtfechanacKeyReleased

    private void txtfechacontKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfechacontKeyReleased
if (!txtidempleado.getText().equals("") && !txtapellido.getText().equals("") && !txtnombre.getText().equals("") && !txtfechanac.getText().equals("") && !txtfechacont.getText().equals("") && !txtjefe.getText().equals(""))
        {
            
            btnguardar.setEnabled(true);
            btneditar.setEnabled(true);
        }
        else
        {
            
            btnguardar.setEnabled(false);
            btneditar.setEnabled(false);
            btneliminar.setEnabled(false);
        }
    }//GEN-LAST:event_txtfechacontKeyReleased

    private void txtjefeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjefeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjefeKeyReleased

    private void txtfotoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfotoKeyReleased
    if (txtfoto.getText().equals(""))
            {
                lblFoto.setIcon ( new ImageIcon (""));
            }
    }//GEN-LAST:event_txtfotoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnfoto;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtbusquedacliente;
    private javax.swing.JTextField txtbusquedafecha;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtciudad;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdtratamiento;
    private javax.swing.JTextField txtext;
    private javax.swing.JTextField txtfechacont;
    private javax.swing.JTextField txtfechanac;
    private javax.swing.JTextField txtfoto;
    private javax.swing.JTextField txtidempleado;
    private javax.swing.JTextField txtjefe;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnotas;
    private javax.swing.JTextField txtpais;
    private javax.swing.JTextField txtregion;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
