/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neptuno;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author EQÚIPO
 */
public class FrmFactura extends javax.swing.JInternalFrame {

    Font fuente = new Font("Dialog", Font.PLAIN, 10);
    PrintJob pj; 
    Graphics pagina;
    static int inc = 110;
    String SubTotal = "0";
    String subt1 = "0";
    String subt2 = "0";
    String subt3 = "0";
    String subt4 = "0";
    String iva = "0";
    double IVA = 0.12;
    String Total = "0";
    
    public void imprimir(String Cliente , String Fecha , String direccion , String telefono , String codigo1 , String codigo2 , String codigo3 , String codigo4 , String nom1
    , String nom2 , String nom3 , String nom4 , String cant1 , String cant2 , String cant3 , String cant4 , String precio1 , String precio2 , String precio3 , String precio4 , String sub1 , String sub2 
    , String sub3 , String sub4 , String Sub , String iva , String descuento , String total)
    {
        try
        {
            pagina = pj.getGraphics();
            pagina.setFont(fuente);
            pagina.setColor(Color.black);
            pagina.drawString(Cliente, 150 , 140);
            pagina.drawString(Fecha, 450 , 140);
            pagina.drawString(direccion , 150 , 170);
            pagina.drawString(telefono , 450 , 170);
            pagina.drawString(codigo1 , 150, 200 + 50);
            pagina.drawString(nom1 , 200, 200 + 50);
            pagina.drawString(cant1 , 350, 200 + 50);
            pagina.drawString(precio1 , 400, 200 + 50);
            pagina.drawString(sub1 , 450, 200 + 50);
            pagina.drawString(codigo2 , 150, 230 + 50);
            pagina.drawString(nom2 , 200, 230 + 50);
            pagina.drawString(cant2 , 350, 230 + 50);
            pagina.drawString(precio2 , 400, 230 + 50);
            pagina.drawString(sub2 , 450, 230 + 50);
            pagina.drawString(codigo3 , 150, 260 + 50);
            pagina.drawString(nom3 , 200, 260 + 50);
            pagina.drawString(cant3 , 350, 260 + 50);
            pagina.drawString(precio3 , 400, 260 + 50);
            pagina.drawString(sub3 , 450, 260 + 50);
            pagina.drawString(codigo4 , 150, 290 + 50);
            pagina.drawString(nom4 , 200, 290 + 50);
            pagina.drawString(cant4 , 350, 290 + 50);
            pagina.drawString(precio4 , 400, 290 + 50);
            pagina.drawString(sub4 , 450, 290 + 50);
            pagina.drawString(Sub , 450, 320 + 50);
            pagina.drawString(iva , 450, 350 + 50);
            pagina.drawString(descuento , 450, 370 + 50);
            pagina.drawString(total , 450, 400 + 50);
            
            pagina.dispose();
            pj.end();
        }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Impresión cancelada...", "Aviso",JOptionPane.WARNING_MESSAGE);
            }
    }



    public FrmFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btneliminar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boxcliente = new javax.swing.JComboBox<>();
        txtfecha = new javax.swing.JTextField();
        txtdirre = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        boxcod1 = new javax.swing.JComboBox<>();
        boxcod2 = new javax.swing.JComboBox<>();
        boxcod3 = new javax.swing.JComboBox<>();
        boxcod4 = new javax.swing.JComboBox<>();
        txtnom1 = new javax.swing.JTextField();
        txtnom2 = new javax.swing.JTextField();
        txtnom3 = new javax.swing.JTextField();
        txtnom4 = new javax.swing.JTextField();
        txtcant1 = new javax.swing.JTextField();
        txtcant2 = new javax.swing.JTextField();
        txtcant3 = new javax.swing.JTextField();
        txtcant4 = new javax.swing.JTextField();
        txtprecio1 = new javax.swing.JTextField();
        txtprecio2 = new javax.swing.JTextField();
        txtprecio3 = new javax.swing.JTextField();
        txtprecio4 = new javax.swing.JTextField();
        txtsub1 = new javax.swing.JTextField();
        txtsub2 = new javax.swing.JTextField();
        txtsub3 = new javax.swing.JTextField();
        txtsub4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        txtiva = new javax.swing.JTextField();
        txtdescuento = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        lblfactura = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/delete.png"))); // NOI18N
        btneliminar.setPreferredSize(new java.awt.Dimension(16, 16));

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/editar.png"))); // NOI18N
        btneditar.setPreferredSize(new java.awt.Dimension(16, 16));

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/nuevo.png"))); // NOI18N
        btnnuevo.setPreferredSize(new java.awt.Dimension(16, 16));

        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/imprimir.jpg"))); // NOI18N
        btnimprimir.setPreferredSize(new java.awt.Dimension(16, 16));
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/save.png"))); // NOI18N
        btnguardar.setPreferredSize(new java.awt.Dimension(16, 16));
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        jLabel1.setText("FACTURA ");

        boxcliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        boxcliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxclienteItemStateChanged(evt);
            }
        });
        boxcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxclienteMouseClicked(evt);
            }
        });
        boxcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxclienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente");

        jLabel3.setText("Fecha");

        jLabel4.setText("Teléfono");

        jLabel5.setText("Dirección");

        jLabel6.setText("Código");

        jLabel7.setText("Nombre");

        jLabel8.setText("Cant.");

        jLabel9.setText("Precio");

        jLabel10.setText("SubT");

        boxcod1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        boxcod1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxcod1ItemStateChanged(evt);
            }
        });
        boxcod1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxcod1MouseClicked(evt);
            }
        });

        boxcod2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        boxcod2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxcod2ItemStateChanged(evt);
            }
        });

        boxcod3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        boxcod3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxcod3ItemStateChanged(evt);
            }
        });

        boxcod4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        boxcod4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxcod4ItemStateChanged(evt);
            }
        });

        txtcant1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcant1KeyReleased(evt);
            }
        });

        txtcant2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcant2KeyReleased(evt);
            }
        });

        txtcant3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcant3KeyReleased(evt);
            }
        });

        txtcant4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcant4KeyReleased(evt);
            }
        });

        txtprecio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecio2ActionPerformed(evt);
            }
        });

        txtprecio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecio4ActionPerformed(evt);
            }
        });

        txtsub1.setText("0");

        txtsub2.setText("0");

        txtsub3.setText("0");

        txtsub4.setText("0");

        jLabel11.setText("SubT");

        jLabel12.setText("IVA 12 %");

        jLabel13.setText("Descuento");

        jLabel14.setText("Total");

        txtdescuento.setText("0");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        lblfactura.setText("XXXX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblfactura)))
                .addContainerGap(426, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxcod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxcod2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxcod3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxcod4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtdirre)
                            .addComponent(boxcliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(12, 12, 12))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTel, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(txtfecha))
                        .addGap(235, 235, 235))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(34, 34, 34))
                            .addComponent(txtnom1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(txtnom2)
                            .addComponent(txtnom3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnom4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel8)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel9))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtcant3)
                                        .addComponent(txtcant4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(13, 13, 13)
                                    .addComponent(txtprecio4))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtcant1)
                                        .addComponent(txtcant2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(17, 17, 17)
                                            .addComponent(txtprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtprecio3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtprecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsub1)
                                    .addComponent(txtsub2)
                                    .addComponent(txtsub3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(txtsub4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(258, 258, 258))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(txtiva)
                    .addComponent(txtdescuento)
                    .addComponent(txtTotal))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblfactura))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdirre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxcod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxcod2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxcod3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxcod4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcant3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcant4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsub4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        pj = Toolkit.getDefaultToolkit().getPrintJob(new Frame(), "PRUEBA", null);
        this.imprimir(boxcliente.getSelectedItem().toString() , txtfecha.getText() , txtdirre.getText() , txtTel.getText() , boxcod1.getSelectedItem().toString() , 
                boxcod2.getSelectedItem().toString() , boxcod3.getSelectedItem().toString() , boxcod4.getSelectedItem().toString() , txtnom1.getText() , txtnom2.getText()
                , txtnom3.getText() , txtnom4.getText() , txtcant1.getText() , txtcant2.getText() , txtcant3.getText() , txtcant4.getText() , txtprecio1.getText() 
                , txtprecio2.getText() , txtprecio3.getText() , txtprecio4.getText() , txtsub1.getText() , txtsub2.getText() , txtsub3.getText() , txtsub4.getText() , txtsubtotal.getText()
        , txtiva.getText() , txtdescuento.getText() , txtTotal.getText());

    }//GEN-LAST:event_btnimprimirActionPerformed

    private void txtprecio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecio2ActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtprecio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecio4ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Factura fac = new Factura("root" , "eran" , "neptuno2017_3" , "localhost");
        fac.conectarFactura();       
        try 
        {
            lblfactura.setText(String.valueOf(fac.numeroFactura()));
            
        } catch (SQLException ex) 
        {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        fac.cerrarFactura();
        
        SimpleDateFormat sdfDate = new SimpleDateFormat("yyyy-MM-dd");
        Date now = new Date();
        String strDate = sdfDate.format(now);
        txtfecha.setText(strDate);  

     
        ResultSet rsFactura = null;
        
        fac.conectarFactura();
        rsFactura = fac.cargarCliente();
        
            
            
        try {
            while(rsFactura.next())
            {
                boxcliente.addItem(rsFactura.getObject(1).toString());
              
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        fac.cerrarFactura();
        
        ResultSet rsid = null;
        fac.conectarFactura();
        rsid = fac.cargarId();
        try {
            while(rsid.next())
            {
                boxcod1.addItem(rsid.getObject(1).toString());
                boxcod2.addItem(rsid.getObject(1).toString());
                boxcod3.addItem(rsid.getObject(1).toString());
                boxcod4.addItem(rsid.getObject(1).toString());
              
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        fac.cerrarFactura();
        
        
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void boxclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxclienteActionPerformed
        
     
    }//GEN-LAST:event_boxclienteActionPerformed

    private void boxclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxclienteMouseClicked
        
    }//GEN-LAST:event_boxclienteMouseClicked

    private void boxclienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxclienteItemStateChanged
        Factura fac = new Factura("root" , "eran" , "neptuno2017_3" , "localhost");
        fac.conectarFactura(); 
        String Direccion = "";
        ResultSet rsdireccion = null;
        rsdireccion = fac.consultarDireccion(boxcliente.getSelectedItem().toString());
        
        
        try {
            while(rsdireccion.next())
            {
                Direccion = rsdireccion.getObject(1).toString();
            } 
        } catch (SQLException ex) {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }

        String Telefono = "";
        ResultSet rsTelefono = null;
        rsTelefono = fac.consultarTelefono(boxcliente.getSelectedItem().toString());
        
        
        try {
            while(rsTelefono.next())
            {
                Telefono = rsTelefono.getObject(1).toString();
            } 
        } catch (SQLException ex) 
        {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        fac.cerrarFactura();
        
        txtdirre.setText(Direccion);
        txtTel.setText(Telefono);
    }//GEN-LAST:event_boxclienteItemStateChanged

    private void boxcod1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxcod1ItemStateChanged
        Factura fac = new Factura("root" , "eran" , "neptuno2017_3" , "localhost");
        fac.conectarFactura(); 
        String Nombre = "";
        ResultSet rsNombre = null;
        rsNombre = fac.consultarNombre(boxcod1.getSelectedItem().toString());
        
        
        try {
            while(rsNombre.next())
            {
                Nombre = rsNombre.getObject(1).toString();
            } 
        } catch (SQLException ex) {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }

        String Precio = "";
        ResultSet rsPrecio = null;
        rsPrecio = fac.consultarPrecio(boxcod1.getSelectedItem().toString());
        
        
        try {
            while(rsPrecio.next())
            {
                Precio = rsPrecio.getObject(1).toString();
            } 
        } catch (SQLException ex) 
        {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        fac.cerrarFactura();
        
        txtnom1.setText(Nombre);
        txtprecio1.setText(Precio);
        
        if (!txtcant1.getText().equals(""))
        {
            subt1 = String.valueOf(Integer.valueOf(txtcant1.getText()) * Double.valueOf(txtprecio1.getText()));
            SubTotal = subt1;
            txtsub1.setText(subt1);
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA );
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
        }
        else
        {
            txtsub1.setText("0");
            SubTotal = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(subt1));
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA);
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
        }


    }//GEN-LAST:event_boxcod1ItemStateChanged

    private void boxcod2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxcod2ItemStateChanged
        Factura fac = new Factura("root" , "eran" , "neptuno2017_3" , "localhost");
        fac.conectarFactura(); 
        String Nombre = "";
        ResultSet rsNombre = null;
        rsNombre = fac.consultarNombre(boxcod2.getSelectedItem().toString());
        
        
        try {
            while(rsNombre.next())
            {
                Nombre = rsNombre.getObject(1).toString();
            } 
        } catch (SQLException ex) {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }

        String Precio = "";
        ResultSet rsPrecio = null;
        rsPrecio = fac.consultarPrecio(boxcod2.getSelectedItem().toString());
        
        
        try {
            while(rsPrecio.next())
            {
                Precio = rsPrecio.getObject(1).toString();
            } 
        } catch (SQLException ex) 
        {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        fac.cerrarFactura();
        
        txtnom2.setText(Nombre);
        txtprecio2.setText(Precio);
        
        if (!txtcant2.getText().equals(""))
        {
            subt2 = String.valueOf(Integer.valueOf(txtcant2.getText()) * Double.valueOf(txtprecio2.getText()));
            SubTotal = String.valueOf(Double.valueOf(subt1) + Double.valueOf(subt2));
            txtsub2.setText(subt2);
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA);
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
        }
        else
        {
            SubTotal = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(subt2));
            txtsub2.setText("0");
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA);
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
            
        }

    }//GEN-LAST:event_boxcod2ItemStateChanged

    private void boxcod3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxcod3ItemStateChanged
        Factura fac = new Factura("root" , "eran" , "neptuno2017_3" , "localhost");
        fac.conectarFactura(); 
        String Nombre = "";
        ResultSet rsNombre = null;
        rsNombre = fac.consultarNombre(boxcod3.getSelectedItem().toString());
        
        
        try {
            while(rsNombre.next())
            {
                Nombre = rsNombre.getObject(1).toString();
            } 
        } catch (SQLException ex) {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }

        String Precio = "";
        ResultSet rsPrecio = null;
        rsPrecio = fac.consultarPrecio(boxcod3.getSelectedItem().toString());
        
        
        try {
            while(rsPrecio.next())
            {
                Precio = rsPrecio.getObject(1).toString();
            } 
        } catch (SQLException ex) 
        {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        fac.cerrarFactura();
        
        txtnom3.setText(Nombre);
        txtprecio3.setText(Precio);
        
        if (!txtcant3.getText().equals(""))
        {
            subt3 = String.valueOf(Integer.valueOf(txtcant3.getText()) * Double.valueOf(txtprecio3.getText()));
            SubTotal = String.valueOf(Double.valueOf(subt1) + Double.valueOf(subt2) + Double.valueOf(subt3));
            txtsub3.setText(subt3);
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA);
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
        }
        else
        {
            SubTotal = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(subt3));
            txtsub3.setText("0");
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA);
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
            
        }

    }//GEN-LAST:event_boxcod3ItemStateChanged

    private void boxcod4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxcod4ItemStateChanged
        Factura fac = new Factura("root" , "eran" , "neptuno2017_3" , "localhost");
        fac.conectarFactura(); 
        String Nombre = "";
        ResultSet rsNombre = null;
        rsNombre = fac.consultarNombre(boxcod4.getSelectedItem().toString());
        
        
        try {
            while(rsNombre.next())
            {
                Nombre = rsNombre.getObject(1).toString();
            } 
        } catch (SQLException ex) {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }

        String Precio = "";
        ResultSet rsPrecio = null;
        rsPrecio = fac.consultarPrecio(boxcod4.getSelectedItem().toString());
        
        
        try {
            while(rsPrecio.next())
            {
                Precio = rsPrecio.getObject(1).toString();
            } 
        } catch (SQLException ex) 
        {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        fac.cerrarFactura();
        
        txtnom4.setText(Nombre);
        txtprecio4.setText(Precio);
        
        if (!txtcant4.getText().equals(""))
        {
            subt4 = String.valueOf(Integer.valueOf(txtcant4.getText()) * Double.valueOf(txtprecio4.getText()));
            SubTotal = String.valueOf(Double.valueOf(subt1) + Double.valueOf(subt2) + Double.valueOf(subt3) + Double.valueOf(subt4));
            txtsub4.setText(subt4);
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA);
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
        }
        else
        {
            SubTotal = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(subt4));
            txtsub4.setText("0");
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA);
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
            
            
        }

    }//GEN-LAST:event_boxcod4ItemStateChanged

    private void txtcant1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcant1KeyReleased
     if (!txtcant1.getText().equals(""))
        {
            subt1 = String.valueOf(Integer.valueOf(txtcant1.getText()) * Double.valueOf(txtprecio1.getText()));
            SubTotal = subt1;
            txtsub1.setText(subt1);
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA );
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
        }
        else
        {
            txtsub1.setText("0");
            SubTotal = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(subt1));
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA);
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
        }
       
    }//GEN-LAST:event_txtcant1KeyReleased

    private void txtcant2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcant2KeyReleased
        
        if (!txtcant2.getText().equals(""))
        {
            subt2 = String.valueOf(Integer.valueOf(txtcant2.getText()) * Double.valueOf(txtprecio2.getText()));
            SubTotal = String.valueOf(Double.valueOf(subt1) + Double.valueOf(subt2));
            txtsub2.setText(subt2);
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA);
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
        }
        else
        {
            SubTotal = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(subt2));
            txtsub2.setText("0");
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA);
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
            
        }
    }//GEN-LAST:event_txtcant2KeyReleased

    private void txtcant3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcant3KeyReleased
       
         if (!txtcant3.getText().equals(""))
        {
            subt3 = String.valueOf(Integer.valueOf(txtcant3.getText()) * Double.valueOf(txtprecio3.getText()));
            SubTotal = String.valueOf(Double.valueOf(subt1) + Double.valueOf(subt2) + Double.valueOf(subt3));
            txtsub3.setText(subt3);
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA);
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
        }
        else
        {
            SubTotal = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(subt3));
            txtsub3.setText("0");
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA);
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
            
        }
    }//GEN-LAST:event_txtcant3KeyReleased

    private void txtcant4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcant4KeyReleased
       
        if (!txtcant4.getText().equals(""))
        {
            subt4 = String.valueOf(Integer.valueOf(txtcant4.getText()) * Double.valueOf(txtprecio4.getText()));
            SubTotal = String.valueOf(Double.valueOf(subt1) + Double.valueOf(subt2) + Double.valueOf(subt3) + Double.valueOf(subt4));
            txtsub4.setText(subt4);
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA);
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
        }
        else
        {
            SubTotal = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(subt4));
            txtsub4.setText("0");
            txtsubtotal.setText(SubTotal);
            iva = String.valueOf(Double.valueOf(SubTotal) * IVA);
            txtiva.setText(iva);
            Total = String.valueOf(Double.valueOf(SubTotal) - Double.valueOf(iva));
            txtTotal.setText(Total);
            
            
        }
    }//GEN-LAST:event_txtcant4KeyReleased

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        Factura fac = new Factura("root" , "eran" , "neptuno2017_3" , "localhost");
        fac.conectarFactura();
       
        String idCliente = "";
        String idEmpleado = "1";
        
        ResultSet rsIdCliente = null;
        rsIdCliente = fac.consultarCliente (boxcliente.getSelectedItem().toString());
        
        
        try {
            while(rsIdCliente.next())
            {
                idCliente = rsIdCliente.getObject(1).toString();
            } 
        } catch (SQLException ex) 
        {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (!boxcliente.getSelectedItem().toString().equals("") && !txtdirre.getText().equals("") && !txtTel.getText().equals("") && (!txtcant1.getText().equals("") || !txtcant2.getText().equals("") || !txtcant3.getText().equals("") || !txtcant4.getText().equals("")))
        {
            JOptionPane.showMessageDialog(null , fac.guardaPedido(lblfactura.getText() , idCliente , idEmpleado ,  txtfecha.getText()));
            
            
            if (!txtcant1.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null , fac.guardaDetalleDePedido(lblfactura.getText() , boxcod1.getSelectedItem().toString() , txtcant1.getText() ,  txtprecio1.getText() , txtsub1.getText()));
            }
           
            if (!txtcant2.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null , fac.guardaDetalleDePedido(lblfactura.getText() , boxcod2.getSelectedItem().toString() , txtcant2.getText() ,  txtprecio2.getText() , txtsub2.getText()));
            }
            if (!txtcant3.getText().equals(""))
            {

                JOptionPane.showMessageDialog(null , fac.guardaDetalleDePedido(lblfactura.getText() , boxcod3.getSelectedItem().toString() , txtcant3.getText() ,  txtprecio3.getText() , txtsub3.getText()));
            }
            if (!txtcant4.getText().equals(""))
            {

                JOptionPane.showMessageDialog(null , fac.guardaDetalleDePedido(lblfactura.getText() , boxcod4.getSelectedItem().toString() , txtcant4.getText() ,  txtprecio4.getText() , txtsub4.getText()));
            }
          
        }
        else
        {
            JOptionPane.showMessageDialog(null , "No se Puede Guardar");
        }
        
        
      
    }//GEN-LAST:event_btnguardarActionPerformed

    private void boxcod1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxcod1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_boxcod1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxcliente;
    private javax.swing.JComboBox<String> boxcod1;
    private javax.swing.JComboBox<String> boxcod2;
    private javax.swing.JComboBox<String> boxcod3;
    private javax.swing.JComboBox<String> boxcod4;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblfactura;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtcant1;
    private javax.swing.JTextField txtcant2;
    private javax.swing.JTextField txtcant3;
    private javax.swing.JTextField txtcant4;
    private javax.swing.JTextField txtdescuento;
    private javax.swing.JTextField txtdirre;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtiva;
    private javax.swing.JTextField txtnom1;
    private javax.swing.JTextField txtnom2;
    private javax.swing.JTextField txtnom3;
    private javax.swing.JTextField txtnom4;
    private javax.swing.JTextField txtprecio1;
    private javax.swing.JTextField txtprecio2;
    private javax.swing.JTextField txtprecio3;
    private javax.swing.JTextField txtprecio4;
    private javax.swing.JTextField txtsub1;
    private javax.swing.JTextField txtsub2;
    private javax.swing.JTextField txtsub3;
    private javax.swing.JTextField txtsub4;
    private javax.swing.JTextField txtsubtotal;
    // End of variables declaration//GEN-END:variables
}
