/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neptuno;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EQÚIPO
 */
public class FrmProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProductos
     */
    public FrmProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtbusquedaproducto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtbusquedanomb = new javax.swing.JTextField();
        btneliminar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        txtcantidad = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        btneditar = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        txtunidadesexistencia = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        txtunidadespedido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtnivel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtsuspendido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblproducto = new javax.swing.JTable();
        txtidproducto = new javax.swing.JTextField();
        txtnompro = new javax.swing.JTextField();
        boxproveedor = new javax.swing.JComboBox<>();
        boxcategoria = new javax.swing.JComboBox<>();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel5.setText("idcategoría");

        jLabel13.setText("Busqueda");

        jLabel6.setText("cantidadporunidad");

        jLabel14.setText("idProducto");

        jLabel7.setText("preciounidad");

        jLabel15.setText("nombreproducto");

        txtbusquedaproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusquedaproductoKeyReleased(evt);
            }
        });

        jLabel8.setText("unidadesenexistencia");

        txtbusquedanomb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusquedanombKeyReleased(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/delete.png"))); // NOI18N
        btneliminar.setPreferredSize(new java.awt.Dimension(16, 16));
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/nuevo.png"))); // NOI18N
        btnnuevo.setPreferredSize(new java.awt.Dimension(16, 16));

        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/editar.png"))); // NOI18N
        btneditar.setPreferredSize(new java.awt.Dimension(16, 16));
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/imprimir.jpg"))); // NOI18N
        btnimprimir.setPreferredSize(new java.awt.Dimension(16, 16));
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/save.png"))); // NOI18N
        btnguardar.setPreferredSize(new java.awt.Dimension(16, 16));
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Mantenimiento");

        txtnivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnivelActionPerformed(evt);
            }
        });

        jLabel2.setText("idProducto");

        txtsuspendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsuspendidoActionPerformed(evt);
            }
        });

        jLabel3.setText("NombreProducto");

        jLabel4.setText("idproveedor");

        jLabel9.setText("unidadesenpedido");

        jLabel10.setText("nivelnuevopedido");

        jLabel11.setText("suspendido");

        tblproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproductoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblproducto);

        txtidproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidproductoActionPerformed(evt);
            }
        });
        txtidproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidproductoKeyReleased(evt);
            }
        });

        txtnompro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnomproKeyReleased(evt);
            }
        });

        boxproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxproveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtprecio, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtunidadesexistencia, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtunidadespedido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtnivel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtsuspendido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtidproducto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtnompro, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(boxcategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                            .addComponent(boxproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(27, 27, 27)
                        .addComponent(txtbusquedaproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtbusquedanomb, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtidproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addComponent(txtnompro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(boxproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(boxcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(txtcantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))
                                    .addComponent(txtunidadesexistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtunidadespedido, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(txtnivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))
                    .addComponent(txtsuspendido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel3)
                    .addComponent(txtbusquedaproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbusquedanomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void txtnivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnivelActionPerformed

    private void txtsuspendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsuspendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsuspendidoActionPerformed

    private void txtidproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidproductoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try 
        {
            Productos productos = new Productos("root" , "eran" , "neptuno2017_3" , "localhost");
            ResultSet rsProveedores = null;
         
            productos.conectarProductos();
            rsProveedores = productos.cargarProveedores();
            
            
            while(rsProveedores.next())
            {
                boxproveedor.addItem(rsProveedores.getObject(1).toString());
              
            }
            productos.cerrarProductos();
        } catch (SQLException ex) 
        {
            Logger.getLogger(FrmProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try 
        {
            Productos productos = new Productos("root" , "eran" , "neptuno2017_3" , "localhost");
            ResultSet rsCategorías = null;
         
            productos.conectarProductos();
            
            rsCategorías = productos.cargarCategorias();
            
            while(rsCategorías.next())
            {
                boxcategoria.addItem(rsCategorías.getObject(1).toString());
              
            }
            productos.cerrarProductos();
        } catch (SQLException ex) 
        {
            Logger.getLogger(FrmProductos.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        Productos producto = new Productos("root" , "eran" , "neptuno2017_3" , "localhost");
        String idProveedor = "", idCategoria = "";
        producto.conectarProductos();
        
        ResultSet rsIdProveedor = null;
        rsIdProveedor = producto.consultarProveedores(boxproveedor.getSelectedItem().toString());
        
        
        try {
            while(rsIdProveedor.next())
            {
                idProveedor = rsIdProveedor.getObject(1).toString();
            } 
        } catch (SQLException ex) {
            Logger.getLogger(FrmProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         ResultSet rsIdCategoria = null;
         rsIdCategoria = producto.consultarCategorias(boxcategoria.getSelectedItem().toString());
         
        try {
            while(rsIdCategoria.next())
            {
                idCategoria = rsIdCategoria.getObject(1).toString();
            }

        } catch (SQLException ex) {
            Logger.getLogger(FrmProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null , producto.guardarProductos(txtidproducto.getText() , txtnompro.getText() , idProveedor ,  idCategoria , txtcantidad.getText() , txtprecio.getText() , txtunidadesexistencia.getText() , txtunidadespedido.getText() , txtnivel.getText() , txtsuspendido.getText()));
        producto.cerrarProductos();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        Productos producto = new Productos("root" , "eran" , "neptuno2017_3" , "localhost");
        producto.conectarProductos();       
        JOptionPane.showMessageDialog(null , producto.eliminarProductos(txtidproducto.getText()));
        producto.cerrarProductos();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        Productos producto = new Productos("root" , "eran" , "neptuno2017_3" , "localhost");
        producto.conectarProductos();
        JOptionPane.showMessageDialog(null , producto.actualizarProductos(txtidproducto.getText() , txtnompro.getText() , boxproveedor.getSelectedItem().toString() ,  boxcategoria.getSelectedItem().toString() , txtcantidad.getText() , txtprecio.getText() , txtunidadesexistencia.getText() , txtunidadespedido.getText() , txtnivel.getText() , txtsuspendido.getText()));
        producto.cerrarProductos();
    }//GEN-LAST:event_btneditarActionPerformed

    private void txtbusquedaproductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaproductoKeyReleased
        try 
        {
            Productos producto = new Productos("root" , "eran" , "neptuno2017_3" , "localhost");
            producto.conectarProductos();
            ResultSet rsPoducto = producto.buscarPorId(txtbusquedaproducto.getText());
            //Para establecer el modelo al JTable
            
            DefaultTableModel modelo = new DefaultTableModel();
            tblproducto.setModel(modelo);
            
            //Para conectarnos a nuestra base de datos
            
            ResultSetMetaData rsMd = rsPoducto.getMetaData();
            
            //La cantidad de columnas que tiene la consulta
            
            int cantidadColumnas = rsMd.getColumnCount();
            
            //Establecer como cabezeras el nombre de las colimnas
            
            for (int posicion = 1 ; posicion <= cantidadColumnas ; posicion ++)
            {
                modelo.addColumn(rsMd.getColumnLabel(posicion));
            }
            //Creando las filas para el JTable
            
            while (rsPoducto.next())
            {
                Object[] fila = new Object[cantidadColumnas];
                for (int posicion = 0; posicion < cantidadColumnas; posicion ++)
                {
                    fila[posicion] = rsPoducto.getObject(posicion + 1);
                }
                modelo.addRow(fila);
                
            }  
            producto.cerrarProductos();
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(FrmProductos.class.getName()).log(Level.SEVERE , null , ex);
        }
    }//GEN-LAST:event_txtbusquedaproductoKeyReleased

    private void txtbusquedanombKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedanombKeyReleased
        try 
        {
            Productos producto = new Productos("root" , "eran" , "neptuno2017_3" , "localhost");
            producto.conectarProductos();
            ResultSet rsPoducto = producto.buscarPorNombreProducto(txtbusquedanomb.getText());
            //Para establecer el modelo al JTable
            
            DefaultTableModel modelo = new DefaultTableModel();
            tblproducto.setModel(modelo);
            
            //Para conectarnos a nuestra base de datos
            
            ResultSetMetaData rsMd = rsPoducto.getMetaData();
            
            //La cantidad de columnas que tiene la consulta
            
            int cantidadColumnas = rsMd.getColumnCount();
            
            //Establecer como cabezeras el nombre de las colimnas
            
            for (int posicion = 1 ; posicion <= cantidadColumnas ; posicion ++)
            {
                modelo.addColumn(rsMd.getColumnLabel(posicion));
            }
            //Creando las filas para el JTable
            
            while (rsPoducto.next())
            {
                Object[] fila = new Object[cantidadColumnas];
                for (int posicion = 0; posicion < cantidadColumnas; posicion ++)
                {
                    fila[posicion] = rsPoducto.getObject(posicion + 1);
                }
                modelo.addRow(fila);
                
            }  
            producto.cerrarProductos();
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(FrmProductos.class.getName()).log(Level.SEVERE , null , ex);
        }
    }//GEN-LAST:event_txtbusquedanombKeyReleased

    private void tblproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductoMouseClicked
        txtidproducto.setText(String.valueOf(tblproducto.getValueAt(tblproducto.getSelectedRow() , 0)));
        txtnompro.setText(String.valueOf(tblproducto.getValueAt(tblproducto.getSelectedRow() , 1)));
        boxproveedor.setSelectedItem(String.valueOf(tblproducto.getValueAt(tblproducto.getSelectedRow() , 2)));
        boxcategoria.setSelectedItem(String.valueOf(tblproducto.getValueAt(tblproducto.getSelectedRow() , 3)));
        txtcantidad.setText(String.valueOf(tblproducto.getValueAt(tblproducto.getSelectedRow() , 4)));
        txtprecio.setText(String.valueOf(tblproducto.getValueAt(tblproducto.getSelectedRow() , 5)));
        txtunidadesexistencia.setText(String.valueOf(tblproducto.getValueAt(tblproducto.getSelectedRow() , 6)));
        txtunidadespedido.setText(String.valueOf(tblproducto.getValueAt(tblproducto.getSelectedRow() , 7)));
        txtnivel.setText(String.valueOf(tblproducto.getValueAt(tblproducto.getSelectedRow() , 8)));
        txtsuspendido.setText(String.valueOf(tblproducto.getValueAt(tblproducto.getSelectedRow() , 9)));
        
        if (!txtidproducto.getText().equals("") && !txtnompro.getText().equals(""))
        {
            btneliminar.setEnabled(true);
            btnguardar.setEnabled(true);
            btneditar.setEnabled(true);
            
        }
        else
        {
            btneliminar.setEnabled(false);
            
        }
     
    }//GEN-LAST:event_tblproductoMouseClicked

    private void txtidproductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidproductoKeyReleased
        if (!txtidproducto.getText().equals("") && !txtnompro.getText().equals(""))
        {
            
            btnguardar.setEnabled(true);
            btneditar.setEnabled(true);
        }
        else
        {
            
            btnguardar.setEnabled(false);
            btneditar.setEnabled(false);
            btneliminar.setEnabled(false);
        }
    }//GEN-LAST:event_txtidproductoKeyReleased

    private void txtnomproKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomproKeyReleased
        if (!txtidproducto.getText().equals("") && !txtnompro.getText().equals(""))
        {
            
            btnguardar.setEnabled(true);
            btneditar.setEnabled(true);
        }
        else
        {
            
            btnguardar.setEnabled(false);
            btneditar.setEnabled(false);
            btneliminar.setEnabled(false);
        }
    }//GEN-LAST:event_txtnomproKeyReleased

    private void boxproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxproveedorActionPerformed

    }//GEN-LAST:event_boxproveedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxcategoria;
    private javax.swing.JComboBox<String> boxproveedor;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblproducto;
    private javax.swing.JTextField txtbusquedanomb;
    private javax.swing.JTextField txtbusquedaproducto;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtidproducto;
    private javax.swing.JTextField txtnivel;
    private javax.swing.JTextField txtnompro;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtsuspendido;
    private javax.swing.JTextField txtunidadesexistencia;
    private javax.swing.JTextField txtunidadespedido;
    // End of variables declaration//GEN-END:variables
}
